- name: install redis component
  hosts: redis
  become: yes
  tasks:
    - name: install epel release repo
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: install remi release repo
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present
        disable_gpg_check: true

    - name: enable redis remi module
      ansible.builtin.dnf:
        name: '@redis:remi-6.2'
        state: present

    - name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^bind 127\.0\.0\.1'
        replace: 'bind 0.0.0.0'
      notify: restart redis

    - name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes

  handlers:
    - name: restart redis
      ansible.builtin.service:
        name: redis
        state: restarted